//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int Id { get; set; }
        public int IdCountry { get; set; }

        [Required(ErrorMessage = "Name Field is required")]
        [MaxLength(50, ErrorMessage = "Name too long, just 50 characters are allowed")]
        public string Name { get; set; }

        [Required(ErrorMessage = "LastName Field is required")]
        [MaxLength(50, ErrorMessage = "LastName too long, just 50 characters are allowed")]
        public string LastName { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Book { get; set; }
    }
}
