//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Script.Serialization;

    public partial class Book
    {
        public int Id { get; set; }
        public int IdAuthor { get; set; }
        public int IdCategory { get; set; }

        [Required(ErrorMessage = "ISBN Field is required")]
        [MaxLength(50, ErrorMessage = "ISBN too long, just 50 characters are allowed")]
        public string ISBN { get; set; }

        [Required(ErrorMessage = "Title Field is required")]
        [MaxLength(50, ErrorMessage = "Title too long, just 50 characters are allowed")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Publisher Field is required")]
        [MaxLength(50, ErrorMessage = "Publisher too long, just 50 characters are allowed")]
        public string Publisher { get; set; }

        [Required(ErrorMessage = "Description Field is required")]
        [MaxLength(200, ErrorMessage = "Description too long, just 200 characters are allowed")]
        public string Description { get; set; }
        [ScriptIgnore(ApplyToOverrides = true)]
        public virtual Author Author { get; set; }
        [ScriptIgnore(ApplyToOverrides = true)]
        public virtual Category Category { get; set; }
    }
}
